name: saturnfs
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - click<8.1.4
  - requests
  - marshmallow>=3.10.0,<4.0.0
  - marshmallow-dataclass
  # Note: 2023.3.0 requires python>=3.8 - decide on min python for this
  - fsspec==2023.1.0
