name: saturnfs
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
      - black>=20.8b1
      - mypy>=1.1.1,<1.2
      - pylint>=2.17.0,<2.18.0
      - pre-commit>=2.9.3
      - types-requests
      - marshmallow-dataclass
