name: Linting

on:
  push:

jobs:
  test:
    name: ${{ matrix.task }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install conda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          python-version: 3.7
          miniconda-version: py37_4.10.3
          activate-environment: saturnfs
          auto-update-conda: false
          environment-file: environment.test.yaml
      - name: Lint
        shell: bash -el {0}
        run: make lint
