name: Linting

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    name: ${{ matrix.task }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
          activate-environment: saturnfs
          auto-update-conda: true
      - name: Install test utils
        shell: bash
        run: conda env update -n saturnfs --file environment.test.yaml
      - name: Lint
        shell: bash
        run: make lint
