name: Linting

on:
  push:

jobs:
  test:
    name: ${{ matrix.task }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install conda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          python-version: 3.7
          miniconda-version: py37_4.9.2
          activate-environment: saturnfs
          auto-update-conda: true
          environment-file: environment.test.yaml
      - name: Lint
        shell: bash
        run: |
          which conda
          which pip
          pip show black
          make lint
